animals:
  - type: Wolf
    weight: 50
    max_count: 30
    speed: 3
    hunger: 8
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 10
      Deer: 15
      Rabbit: 60
      Mouse: 80
      Goat: 60
      Sheep: 70
      Boar: 15
      Buffalo: 10
      Duck: 40
      Caterpillar: 0
      Plant: 0
  - type: Boa
    weight: 15
    max_count: 30
    speed: 1
    hunger: 3
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 15
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 20
      Mouse: 40
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 10
      Caterpillar: 0
      Plant: 0
  - type: Fox
    weight: 8
    max_count: 30
    speed: 2
    hunger: 2
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 70
      Mouse: 90
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 60
      Caterpillar: 40
      Plant: 0
  - type: Bear
    weight: 500
    max_count: 5
    speed: 2
    hunger: 80
    catch_chance:
      Wolf: 0
      Boa: 80
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 40
      Deer: 80
      Rabbit: 80
      Mouse: 90
      Goat: 70
      Sheep: 70
      Boar: 50
      Buffalo: 20
      Duck: 10
      Caterpillar: 0
      Plant: 0
  - type: Eagle
    weight: 6
    max_count: 20
    speed: 3
    hunger: 1
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 10
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 90
      Mouse: 90
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 80
      Caterpillar: 0
      Plant: 0
  - type: Horse
    weight: 400
    max_count: 20
    speed: 4
    hunger: 60
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Caterpillar: 0
      Plant: 100
  - type: Deer
    weight: 300
    max_count: 20
    speed: 4
    hunger: 50
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Caterpillar: 0
      Plant: 100
  - type: entity.Rabbit
    weight: 2
    max_count: 150
    speed: 2
    hunger: 0.45
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Caterpillar: 0
      Plant: 100
  - type: Mouse
    weight: 0.05
    max_count: 500
    speed: 1
    hunger: 0.01
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Caterpillar: 90
      Plant: 100
  - type: Goat
    weight: 60
    max_count: 140
    speed: 3
    hunger: 10
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Caterpillar: 0
      Plant: 100
  - type: Sheep
    weight: 70
    max_count: 140
    speed: 3
    hunger: 15
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Caterpillar: 0
      Plant: 100
  - type: Boar
    weight: 400
    max_count: 50
    speed: 2
    hunger: 50
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 50
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Caterpillar: 90
      Plant: 100
  - type: Buffalo
    weight: 700
    max_count: 10
    speed: 3
    hunger: 100
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Caterpillar: 0
      Plant: 100
  - type: Duck
    weight: 1
    max_count: 200
    speed: 4
    hunger: 0.15
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Caterpillar: 90
      Plant: 100
  - type: Caterpillar
    weight: 0.01
    max_count: 1000
    speed: 0
    hunger: 0
    catch_chance:
      Wolf: 0
      Boa: 0
      Fox: 0
      Bear: 0
      Eagle: 0
      Horse: 0
      Deer: 0
      Rabbit: 0
      Mouse: 0
      Goat: 0
      Sheep: 0
      Boar: 0
      Buffalo: 0
      Duck: 0
      Caterpillar: 0
      Plant: 100